// This file is generated by WOWCube SDK project wizard
//
// Application UUID: NjHjFvEg3I
//

#include <stdint.h>
#include "AppManager.h"
#include "tilt_beta.h"

// Application initialization callback. Called once when CUB application starts
void OnInit(Cubios::AppManager& appMgr) 
{
    appMgr.SetApplication(new tilt_beta, "NjHjFvEg3I");
}

// Called every "tick" of cubeapp application loop
void tilt_beta::on_Tick(uint32_t, uint32_t)
{
}

// Called every time device is about to render visuals
void tilt_beta::on_Render(std::array<Cubios::Screen, 3>& screens)
{
    for (size_t i = 0; i < screens.size(); i++)
    {
        Cubios::GFX_setRenderTarget(screens[i].ID());
        Cubios::GFX_clear(0xFF000000);
    }

    for (size_t i = 0; i < screens.size(); i++)
    {
        if ((int)this->Module == 0 && screens[i].ID() == 0)
        {
            Cubios::GFX_setRenderTarget(screens[i].ID());
            Cubios::GFX_drawRectangle(RECT_X, RECT_Y, RECT_WIDTH, RECT_HEIGHT, 0xFFFFFFFF);
            break;
        }
    }

    Cubios::GFX_render();
}

// "Physics" callback. Called recurrently with ~33ms resolution
void tilt_beta::on_PhysicsTick(const std::array<Cubios::Screen, 3>& screens)
{
}

// Programmable timer callback (unused)
void tilt_beta::on_Timer(uint8_t)
{
}

// Cube topology change callback (unused)
void tilt_beta::on_Twist(const Cubios::TOPOLOGY_twistInfo_t&)
{
}

// Inner network callback (unused)
void tilt_beta::on_Message(uint32_t type, uint8_t* pkt, u32_t size)
{
}

// External data transfer callback (unused)
void tilt_beta::on_ExternalMessage(uint8_t*, u32_t)
{
}

// Screen pat callback (unused)
void tilt_beta::on_Pat(uint32_t)
{
}

// Called before the application quits
void tilt_beta::on_Close()
{
}